### ISSUE TITLE
引用1.0.8运行项目直接闪退

### ISSUE THREAD

**Issue by zy654781296** [lakehubo/HBanner#26]
引用1.0.8运行项目直接闪退

   java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.dhcc.hbanner/com.dhcc.hbanner.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.dhcc.hbanner.MainActivity" on path: DexPathList[[zip file "/data/app/com.dhcc.hbanner-UAD9KU78FaAjtpSnQ9GpXw==/base.apk"],nativeLibraryDirectories=[/data/app/com.dhcc.hbanner-UAD9KU78FaAjtpSnQ9GpXw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2757)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dhcc.hbanner.MainActivity" on path: DexPathList[[zip file "/data/app/com.dhcc.hbanner-UAD9KU78FaAjtpSnQ9GpXw==/base.apk"],nativeLibraryDirectories=[/data/app/com.dhcc.hbanner-UAD9KU78FaAjtpSnQ9GpXw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:173) 
        at android.app.ActivityThread.main(ActivityThread.java:6698) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.dhcc.hbanner-UAD9KU78FaAjtpSnQ9GpXw==/base.apk because: Failure to verify dex file '/data/app/com.dhcc.hbanner-UAD9KU78FaAjtpSnQ9GpXw==/base.apk': Bad method handle type 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:681)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:714)
        at android.app.LoadedApk.getResources(LoadedApk.java:941)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2254)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5755)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)

**Comment by lakehubo** [comment]
您好，这应该不是我库的问题
