### ISSUE TITLE
如果想在View里添加HBanner，ViewPager要如何创建

### ISSUE THREAD

**Issue by yylqn** [lakehubo/HBanner#50]
直接用代码new完添加 报
java.lang.IllegalArgumentException: your viewPager has not attached,it will can not get the handler!
        at com.lake.hbanner.HBannerImp.checkViewAttached(HBannerImp.java:460)
        at com.lake.hbanner.HBannerImp.<init>(HBannerImp.java:97)
        at com.lake.hbanner.HBanner$-CC.create(HBanner.java:151)

**Comment by lakehubo** [comment]
报该错是因为viewpager还未挂载到界面上，所以无法获取handler，可以参考app模块下MainActivity内的监听界面回调

**Comment by yylqn** [comment]
app模块下MainActivity是静态写好布局的嘛。。 我是说 如果想在view里动态添加HBanner， 这个view也是纯代码的， 那么viewpager要怎么创建。。 1.1版本之前我都是可以动态添加上去的

**Comment by zgbilltalent** [comment]
这个问题有结果吗 ？

**Comment by zgbilltalent** [comment]
这个框架是不是有问题了 your viewPager has not attached,it will can not get the handler! 啥问题啊

**Comment by yylqn** [comment]
> 这个问题有结果吗 ？

没，后面改用其他框架了

**Comment by zgbilltalent** [comment]
这个问题 我已经修复，可以尝试 等1000ms 再调用可以解决问题
