### ISSUE TITLE
android.view.WindowManager$BadTokenException:  异常

### ISSUE THREAD

**Issue by 673195872** [lakehubo/HBanner#65]
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nbicc.hbanner, PID: 5366
    android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1243)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:404)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
        at android.app.Dialog.show(Dialog.java:363)
        at android.app.AlertDialog$Builder.show(AlertDialog.java:1132)
        at android.widget.VideoView$5.onError(VideoView.java:615)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3565)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:238)
        at android.os.Looper.loop(Looper.java:349)
        at android.app.ActivityThread.main(ActivityThread.java:8241)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

没找到代码错误的位置

**Comment by lhflihongfang** [comment]
老哥，解决了吗？我也遇到了
